### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by conrad-mo** [yrdsb-peths/final-project-p1c#2]
- [ ] Utilize stacks for health. Push and pop
- [ ] Use quicksort for sorting algo and recursive algo for high scores
- [ ] Implement recursion somewhere else? (Ex. map gen, enemy spawning)
- [ ] Create image assets
